//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_commerce_Web_Project.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Order
    {
        public int OrderId { get; set; }
        public string CustomerName { get; set; }
        public string Address { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public string Action { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> PhoneNumber { get; set; }
    }
}
